"""
synthetic_demo.py
==================
AW IP Holdings Inc. | Public demo waveform synthesis.

Generates physically-styled precursor waveforms for the public PRECEPT
Scout demo. Kept entirely separate from tc_engine_v3.py so no proprietary
engine internals are involved in signal generation.

Demo waveforms exist purely to drive the REAL TCEngine end-to-end so
prospective buyers see authentic channel/CCI/persistence/confidence
behavior on representative inputs — not pre-scripted numbers.

IMPORTANT: All signals are SYNTHETIC DEMONSTRATION WAVEFORMS.
They are not recordings from real earthquakes, volcanoes, or infrastructure.
They are modeled on documented precursor dynamics to produce representative
engine behavior for evaluation purposes only.

Precursor archetypes:
  slow_fatigue         — gradual amplitude growth, increasing kurtosis
  bearing_fault        — harmonic sidebands with amplitude modulation
  fracture_growth      — intermittent transients, frequency drift
  harmonic_lock        — resonance migration with phase coupling
  chaotic_transition   — colored 1/f noise transitioning to chaos
  thermal_instability  — envelope modulation, changing crest factor
  fault_cascade        — multi-stage burst escalation
  resonance_shift      — spectral centroid migration
"""
from __future__ import annotations

import numpy as np
from typing import Dict, List, Tuple, Any

# ── Type aliases ──────────────────────────────────────────────────────────────
WaveformArray = np.ndarray
DemoMetadata  = Dict[str, Any]

WINDOW_SIZE = 128
_N_SAMPLES  = 1024
_STEP       = 32

# Safe bounds — clamp all profile values on ingestion
_MIN_ONSET    = 0.05
_MAX_ONSET    = 0.80
_MIN_SEVERITY = 0.10
_MAX_SEVERITY = 1.00

PUBLIC_DEMO_DISCLAIMER = (
    "Synthetic demonstration waveform. Generated by controlled synthesis "
    "to model representative precursor dynamics. Not a recording from real "
    "geophysical or industrial instrumentation. Engine analysis is real — "
    "input signal is synthetic."
)


# ── COLORED NOISE ─────────────────────────────────────────────────────────────

def _pink_noise(n: int, rng: np.random.Generator) -> np.ndarray:
    """1/f (pink) noise — more realistic background than white noise."""
    white    = rng.standard_normal(n)
    fft      = np.fft.rfft(white)
    freqs    = np.fft.rfftfreq(n)
    freqs[0] = 1.0
    fft     /= np.sqrt(freqs)
    sig      = np.fft.irfft(fft, n=n)
    return sig / (np.std(sig) + 1e-9)


# ── PRECURSOR ARCHETYPES ──────────────────────────────────────────────────────
# All functions share the same signature:
#   (n, severity, seed, onset_frac) -> np.ndarray
# onset_frac is wired from DEMO_PROFILES — never hardcoded inside functions.

def _slow_fatigue(n: int, severity: float, seed: int,
                  onset_frac: float = 0.2) -> np.ndarray:
    rng   = np.random.default_rng(seed)
    t     = np.linspace(0, 4 * np.pi, n)
    sig   = _pink_noise(n, rng) * 0.08
    onset = int(n * onset_frac)
    ramp  = np.zeros(n)
    ramp[onset:] = np.power(np.linspace(0, 1, n - onset), 1.5) * severity
    sig  += ramp * np.sin(1.2 * t + rng.uniform(0, np.pi))
    n_spikes   = int(severity * 18)
    spike_locs = rng.integers(onset, n, size=n_spikes)
    for loc in spike_locs:
        width = rng.integers(2, 6)
        amp   = rng.uniform(0.3, severity * 1.2)
        sig[loc:min(loc + width, n)] += amp * rng.choice([-1, 1])
    return sig


def _bearing_fault(n: int, severity: float, seed: int,
                   onset_frac: float = 0.15) -> np.ndarray:
    rng       = np.random.default_rng(seed)
    t         = np.linspace(0, 8 * np.pi, n)
    sig       = _pink_noise(n, rng) * 0.06
    onset     = int(n * onset_frac)
    f_carrier = 0.8 + rng.uniform(-0.1, 0.1)
    ramp      = np.zeros(n)
    ramp[onset:] = np.linspace(0, severity, n - onset)
    for h in range(1, 5):
        amp  = severity / (h * 1.4)
        sig += ramp * amp * np.sin(h * f_carrier * t + rng.uniform(0, 2 * np.pi))
    f_fault = 0.15 + rng.uniform(-0.02, 0.02)
    mod     = 1 + ramp * 0.6 * np.sin(f_fault * t)
    sig    *= mod
    return sig


def _fracture_growth(n: int, severity: float, seed: int,
                     onset_frac: float = 0.25) -> np.ndarray:
    rng        = np.random.default_rng(seed)
    sig        = _pink_noise(n, rng) * 0.05
    onset      = int(n * onset_frac)
    freq_drift = np.linspace(0.4, 0.4 + severity * 0.6, n)
    phase      = np.cumsum(freq_drift) / n * 2 * np.pi
    ramp       = np.zeros(n)
    ramp[onset:] = np.linspace(0, severity * 0.7, n - onset)
    sig       += ramp * np.sin(phase)
    n_bursts    = int(3 + severity * 12)
    burst_times = np.sort(rng.integers(onset, n, size=n_bursts))
    for bt in burst_times:
        dur   = rng.integers(3, 10)
        amp   = rng.uniform(0.2, severity * 1.5)
        decay = np.exp(-np.linspace(0, 4, dur))
        end   = min(bt + dur, n)
        sig[bt:end] += amp * decay[:end - bt] * rng.choice([-1, 1])
    return sig


def _harmonic_lock(n: int, severity: float, seed: int,
                   onset_frac: float = 0.2) -> np.ndarray:
    rng     = np.random.default_rng(seed)
    t       = np.linspace(0, 10 * np.pi, n)
    sig     = _pink_noise(n, rng) * 0.07
    onset   = int(n * onset_frac)
    f_base  = 0.5
    f_shift = np.linspace(0, severity * 0.5, n)
    phase   = np.cumsum(f_base + f_shift) / n * 2 * np.pi
    ramp    = np.zeros(n)
    ramp[onset:] = np.linspace(0, severity, n - onset)
    sig    += ramp * np.sin(phase)
    for sb in [0.9, 1.1, 2.0]:
        sig += ramp * (severity * 0.3) * np.sin(
            sb * f_base * t + rng.uniform(0, np.pi))
    return sig


def _chaotic_transition(n: int, severity: float, seed: int,
                        onset_frac: float = 0.3) -> np.ndarray:
    rng   = np.random.default_rng(seed)
    onset = int(n * onset_frac)
    sig   = _pink_noise(n, rng) * 0.1
    r_chaos   = 3.6 + severity * 0.35
    x         = 0.5
    chaos_sig = np.zeros(n - onset)
    for i in range(len(chaos_sig)):
        x = r_chaos * x * (1 - x)
        chaos_sig[i] = x - 0.5
    blend      = np.linspace(0, severity, n - onset)
    sig[onset:] += blend * chaos_sig
    burst_start = int(n * max(onset_frac + 0.45, 0.82))
    if burst_start < n:
        sig[burst_start:] += rng.normal(0, severity * 0.8, n - burst_start)
    return sig


def _thermal_instability(n: int, severity: float, seed: int,
                         onset_frac: float = 0.1) -> np.ndarray:
    rng   = np.random.default_rng(seed)
    t     = np.linspace(0, 8 * np.pi, n)
    sig   = _pink_noise(n, rng) * 0.06
    onset = int(n * onset_frac)
    drift = np.zeros(n)
    drift[onset:] = np.sin(
        np.linspace(0, severity * np.pi, n - onset)) * severity * 0.4
    sig  += drift
    n_spikes  = int(4 + severity * 10)
    positions = np.linspace(onset, n - 10, n_spikes).astype(int)
    for i, pos in enumerate(positions):
        amp = severity * (0.2 + 0.8 * i / max(n_spikes, 1))
        sig[pos:min(pos + 4, n)] += amp * rng.choice([-1, 1])
    env_freq = 0.2 + rng.uniform(-0.05, 0.05)
    envelope = 1 + np.linspace(0, severity * 0.5, n) * np.abs(
        np.sin(env_freq * t))
    sig *= envelope
    return sig


def _fault_cascade(n: int, severity: float, seed: int,
                   onset_frac: float = 0.15) -> np.ndarray:
    rng        = np.random.default_rng(seed)
    sig        = _pink_noise(n, rng) * 0.05
    onset      = int(n * onset_frac)
    n_stages   = 3
    stage_size = (n - onset) // n_stages
    for stage in range(n_stages):
        start = onset + stage * stage_size
        end   = min(start + stage_size, n)
        amp   = severity * (0.3 + 0.35 * stage)
        half  = (end - start) // 2
        buildup = np.linspace(0, amp * 0.4, half)
        burst   = rng.normal(0, amp, end - start - half)
        sig[start:start + half] += buildup * np.sin(
            np.linspace(0, (stage + 1) * np.pi, half))
        sig[start + half:end] += burst
    return sig


def _resonance_shift(n: int, severity: float, seed: int,
                     onset_frac: float = 0.2) -> np.ndarray:
    rng     = np.random.default_rng(seed)
    sig     = _pink_noise(n, rng) * 0.06
    onset   = int(n * onset_frac)
    f_start = 0.3 + rng.uniform(-0.05, 0.05)
    f_end   = f_start + severity * 0.7
    freqs   = np.linspace(f_start, f_end, n)
    phase   = np.cumsum(freqs) / n * 2 * np.pi
    ramp    = np.zeros(n)
    ramp[onset:] = np.linspace(0, severity, n - onset)
    sig    += ramp * np.sin(phase)
    sig    += ramp * (severity * 0.25) * np.sin(
        2 * phase + rng.uniform(0, np.pi))
    return sig


# ── ARCHETYPE REGISTRY ────────────────────────────────────────────────────────

_ARCHETYPES: Dict[str, Any] = {
    "slow_fatigue":        _slow_fatigue,
    "bearing_fault":       _bearing_fault,
    "fracture_growth":     _fracture_growth,
    "harmonic_lock":       _harmonic_lock,
    "chaotic_transition":  _chaotic_transition,
    "thermal_instability": _thermal_instability,
    "fault_cascade":       _fault_cascade,
    "resonance_shift":     _resonance_shift,
}

_FALLBACK_PROFILE: Dict[str, Any] = {
    "archetype":  "fault_cascade",
    "onset_frac": 0.35,
    "severity":   0.60,
    "seed":       999,
}

DEMO_PROFILES: Dict[str, Dict[str, Dict[str, Any]]] = {
    "seismic": {
        "FAULT-CASCADE-01": {"archetype": "fault_cascade",       "onset_frac": 0.15, "severity": 0.88, "seed": 4001},
        "FAULT-PACIFIC-07": {"archetype": "chaotic_transition",  "onset_frac": 0.55, "severity": 0.45, "seed": 4002},
        "NETWORK-ARRAY-B":  {"archetype": "slow_fatigue",        "onset_frac": 0.30, "severity": 0.68, "seed": 4003},
    },
    "volcanic": {
        "VOLCANO-ALPHA-01": {"archetype": "harmonic_lock",       "onset_frac": 0.20, "severity": 0.82, "seed": 5001},
        "TREMOR-ARRAY-03":  {"archetype": "resonance_shift",     "onset_frac": 0.40, "severity": 0.60, "seed": 5002},
        "VENT-MONITOR-07":  {"archetype": "fracture_growth",     "onset_frac": 0.60, "severity": 0.40, "seed": 5003},
    },
    "structural": {
        "BRIDGE-HWY401-N":  {"archetype": "bearing_fault",       "onset_frac": 0.25, "severity": 0.79, "seed": 6001},
        "DAM-NIAGARA-S":    {"archetype": "thermal_instability", "onset_frac": 0.50, "severity": 0.55, "seed": 6002},
        "TUNNEL-BORE-12":   {"archetype": "slow_fatigue",        "onset_frac": 0.65, "severity": 0.35, "seed": 6003},
    },
}


# ── BOUNDS GUARDS ─────────────────────────────────────────────────────────────

def _safe_profile(domain: str, asset: str) -> Tuple[str, Dict[str, Any]]:
    """
    Resolve domain safely, look up profile, clamp severity and onset_frac.
    Returns (resolved_domain, clamped_profile).
    resolved_domain may differ from domain if domain was unknown.
    """
    resolved_domain = domain if domain in DEMO_PROFILES else "seismic"
    profile = DEMO_PROFILES[resolved_domain].get(asset, _FALLBACK_PROFILE)
    return resolved_domain, {
        **profile,
        "severity":   float(np.clip(profile.get("severity",   0.6), _MIN_SEVERITY, _MAX_SEVERITY)),
        "onset_frac": float(np.clip(profile.get("onset_frac", 0.3), _MIN_ONSET,    _MAX_ONSET)),
    }


def _normalize(sig: np.ndarray) -> WaveformArray:
    """Normalize signal to [-1, 1] — required by engine input guard."""
    peak = float(np.max(np.abs(sig))) + 1e-9
    return (sig / peak).astype(float)


# ── PUBLIC API ────────────────────────────────────────────────────────────────

def get_assets(domain: str) -> List[str]:
    """Return list of known demo asset keys for a domain. Useful for UI dropdowns."""
    resolved = domain if domain in DEMO_PROFILES else "seismic"
    return list(DEMO_PROFILES[resolved].keys())


def get_demo_tape(domain: str, asset: str) -> Tuple[WaveformArray, DemoMetadata]:
    """
    Generate a full synthetic precursor tape for a given domain/asset.
    Returns (waveform, metadata).
    Metadata is safe to include in API responses — no engine internals exposed.
    """
    resolved_domain, profile = _safe_profile(domain, asset)

    # Safe archetype lookup — falls back to fault_cascade if archetype unknown
    fn = _ARCHETYPES.get(
        profile["archetype"],
        _ARCHETYPES[_FALLBACK_PROFILE["archetype"]],
    )

    raw = fn(
        n          = _N_SAMPLES,
        severity   = profile["severity"],
        seed       = profile["seed"],
        onset_frac = profile["onset_frac"],
    )

    meta: DemoMetadata = {
        "profile_id":        f"{resolved_domain}:{asset}:{profile['archetype']}",
        "archetype":         profile["archetype"],
        "synthetic":         True,
        "asset":             asset,
        "domain":            resolved_domain,
        "requested_domain":  domain,
        "severity":          profile["severity"],
        "onset_frac":        profile["onset_frac"],
        "disclaimer":        PUBLIC_DEMO_DISCLAIMER,
    }
    return _normalize(raw), meta


def get_window(domain: str, asset: str,
               scan_index: int) -> Tuple[WaveformArray, DemoMetadata]:
    """
    Return the windowed slice for a given scan count, looping the tape.
    Returns (window, metadata).
    """
    scan_index          = max(0, int(scan_index))
    tape, meta          = get_demo_tape(domain, asset)
    total_windows       = (len(tape) - WINDOW_SIZE) // _STEP + 1
    idx                 = scan_index % max(total_windows, 1)
    start               = idx * _STEP
    meta["scan_index"]    = scan_index
    meta["window_index"]  = idx
    meta["total_windows"] = total_windows
    return tape[start:start + WINDOW_SIZE], meta
